name: cinemaps
description: A movie locations app built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.1
  image: ^4.1.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  share_plus: ^7.0.0
  timeago: ^3.3.0
  shared_preferences: ^2.2.2
  js: ^0.7.1
  # Temporarily commenting out Firebase packages
  # firebase_core: ^2.24.2
  # firebase_core_web: ^2.10.0
  # firebase_auth: ^4.15.3
  # firebase_auth_web: ^5.8.13
  # firebase_storage: ^11.5.6
  # firebase_storage_web: ^3.6.22
  # cloud_firestore: ^4.13.6
  # cloud_firestore_web: ^3.8.10
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/ui/
    - assets/images/movies/
    - assets/images/gallery/
