// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5O4q6igp28CB8YSbBkaIr7zTWGIDvks0',
    appId: '1:296748595332:web:b1e40bcbdfa6e6797f6ad1',
    messagingSenderId: '296748595332',
    projectId: 'cinebase-db6f2',
    authDomain: 'cinebase-db6f2.firebaseapp.com',
    storageBucket: 'cinebase-db6f2.firebasestorage.app',
    measurementId: 'G-1D14QT2DSE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByOHr2ntiTGoppER7sDFujnl8rNYftj08',
    appId: '1:296748595332:ios:823054f37d4d04fb7f6ad1',
    messagingSenderId: '296748595332',
    projectId: 'cinebase-db6f2',
    storageBucket: 'cinebase-db6f2.firebasestorage.app',
    iosClientId: '296748595332-2t00hp5so5jjo8f4gr216778endtv0jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaps',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByOHr2ntiTGoppER7sDFujnl8rNYftj08',
    appId: '1:296748595332:ios:823054f37d4d04fb7f6ad1',
    messagingSenderId: '296748595332',
    projectId: 'cinebase-db6f2',
    storageBucket: 'cinebase-db6f2.firebasestorage.app',
    iosClientId: '296748595332-2t00hp5so5jjo8f4gr216778endtv0jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaps',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoGgNuUBlQn6amUJHqgOo93lywFS1EOkI',
    appId: '1:296748595332:android:b5b1db0ac748ac2f7f6ad1',
    messagingSenderId: '296748595332',
    projectId: 'cinebase-db6f2',
    storageBucket: 'cinebase-db6f2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5O4q6igp28CB8YSbBkaIr7zTWGIDvks0',
    appId: '1:296748595332:web:b1e40bcbdfa6e6797f6ad1',
    messagingSenderId: '296748595332',
    projectId: 'cinebase-db6f2',
    authDomain: 'cinebase-db6f2.firebaseapp.com',
    storageBucket: 'cinebase-db6f2.firebasestorage.app',
    measurementId: 'G-1D14QT2DSE',
  );

}